name: emily
description: Android remote client for SoftBank Mimamori phones
repository: https://github.com/jcayzac/emily
version: 1.0.0+10000
publish_to: 'none'

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.12.8 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  json_serializable: ^3.3.0

  # UI
  flutter_localizations:
    sdk: flutter
  select_dialog: ^1.1.0

  # Services
  permission_handler: ^5.0.0
  contacts_service: ^0.4.6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
